name: video_trimmer
description: A Flutter package for trimming videos. This supports retrieving, trimming, and storage of trimmed video files to the file system.
version: 0.3.5
homepage: https://github.com/sbis04/video_trimmer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^3.0.0-nullsafety.2
  video_player: ^2.0.0-nullsafety.7
  flutter_ffmpeg: ^0.3.0
  video_thumbnail: ^0.2.5+1
  path_provider: ^1.6.27
  intl: ^0.17.0-nullsafety.2
  path: ^1.8.0-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  pedantic: ^1.10.0-nullsafety.3

flutter:
